# Generated by Django 5.1 on 2024-09-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_movies', '0006_remove_book_buy_link_remove_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='character_vs_plot_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='emotional_tone_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='narrative_style_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='pace_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='romance_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='setting_score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='world_building_importance_score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.URLField(blank=True, default='https://via.placeholder.com/150'),
        ),
    ]
